version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumnes:
      - ./:/app
    command: >
      sh -c "uvicorn api.main:app --host 0.0.0.0 --ports 8000"
